apiVersion: skaffold/v3
kind: Config
metadata:
  name: random-pets
build:
  tagPolicy:
    dateTime:
      format: "2006-01-02_15-04-05.999_MST"
      timezone: "Local"
  artifacts:
    - image: asia-northeast1-docker.pkg.dev/qwiklabs-gcp-01-9d31d1663a81/app-repo/random-pets
      context: .
      docker:
        buildArgs:
          app_version: "{{ .APP_VERSION }}"
        dockerfile: lab-02/pets-api/Dockerfile
  local:
    useBuildkit: true
    push: true
deploy:
  cloudrun: {}
manifests:
  rawYaml:
    - manifest.yaml
